package com.eiyooooo.adblink.entity

enum class ConnectionState {
    DISCONNECTED,
    CONNECTING,
    CONNECTING_AWAITING_AUTHORIZATION,
    CONNECTED_USB,
    CONNECTED_TLS,
    CONNECTED_TCP,
    CONNECTION_FAILED_TIMEOUT,
    CONNECTION_FAILED_UNAUTHORIZED,
    CONNECTION_FAILED_PAIRING_REQUIRED,
    CONNECTION_FAILED_HOST_UNREACHABLE,
    CONNECTION_FAILED_UNKNOWN
}

val connectedStateList = listOf(
    ConnectionState.CONNECTED_USB,
    ConnectionState.CONNECTED_TLS,
    ConnectionState.CONNECTED_TCP
)

val failedStateList = listOf(
    ConnectionState.CONNECTION_FAILED_TIMEOUT,
    ConnectionState.CONNECTION_FAILED_UNAUTHORIZED,
    ConnectionState.CONNECTION_FAILED_PAIRING_REQUIRED,
    ConnectionState.CONNECTION_FAILED_HOST_UNREACHABLE,
    ConnectionState.CONNECTION_FAILED_UNKNOWN
)
